http://iamtrask.github.io/2015/07/12/basic-python-network/

In [278]:
# Example 1 : 2 layer neural network

import numpy as np

# sigmoid function
def nonlin(x, deriv=False):
    if(deriv==True):
        return (1/(1+np.exp(-x)))*(1-(1/(1+np.exp(-x))))
    return 1/(1+np.exp(-x))

# input dataset, 4*3
X = np.array([ [0,0,1],
                 [0,1,1],
                 [1,0,1],
                 [1,1,1]])

# output dataset
y = np.array([[0,0,1,1]]).T #transposed -> now we have 4*1, not 1*4

# seed random numbers to make calculation
# deterministic (just a good practic)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) -1

for iter in range(100000):
    
    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    
    # how much did we miss?
    l1_error = y - l1
    
    # multiply how much we missed by the
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1, True)
    
    # update weights
    syn0 += np.dot(l0.T, l1_delta)
    
print ("Output After Training:")
print (l1)

Output After Training:
[[  7.20249792e-05]
 [  4.80131948e-05]
 [  9.99959301e-01]
 [  9.99938947e-01]]


In [ ]:
#Example 2 : deep learning - 3 layer neural network
import numpy as np

def nonlin(x, deriv=False):
    if deriv:
        return (1/(1+np.exp(-x)))*(1-(1/(1+np.exp(-x))))
    return 1/(1+np.exp(-x))

X = np.array(   [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1])

Y = np.array([[0],
              [1],
              [1],
              [0]])

np.random.seed(1)

# randomly initialize our weights with mean 0
# (b-a)*np.random.random((row,col)) + a
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1 

for j in xrange(60000):
    
    # Feed forward through layers 0, 1 and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0)) # 4*3 and 3*4 -> 4*4
    l2 = nonlin(np.dot(l1,syn1)) # 4*4 and 4*1 -> 4*1
    
    # Error - how much did we miss the target value?
    l2_error = y - l2
    
    if (j % 10000) == 0:
        print ("Error:" + str(np.mean(np.abs(l2_error))))
    
    # Update : in what direction is the target value?
    # were we really sure? If so, don't change too much.
    l2_delta = l2_error * nonlin(l2, deriv=True)
    
    # how much did each l1 value contribute to the l2 error?
    l1_error = l2_delta.dot(syn1.T)
    
    # in what direction is the target l1? 
    l1_delta = l1_error * nonlin(l1, deriv=True)
    
    syn1 += np.dot(l1.T, l2_delta)
    syn0 += np.dot(l0.T, l1_delta)

In [194]:
a = np.array( [[0,0,1,2]])
b = np.array( [[0,1,1,2]])
np.dot(a.T, b) # 4*1 and 1*4 -> 4*4
np.dot(a, b.T) # 1*4 and 4*1 -> 1*1
a*b # elementwise calculation

array([[0, 0, 1, 4]])

In [178]:
np.random.seed(3)
np.random.random(1)

array([ 0.5507979])

In [199]:
1/(1+np.exp(0))

0.5

In [269]:
for i in range(-5, 6):
    print(nonlin(i, deriv=True))
    
print('\nnonlin of deriv\n')
for i in range(-5, 6):
    print(nonlin(i))
    
print('nonlin')

0.00664805667079
0.0176627062133
0.0451766597309
0.104993585404
0.196611933241
0.25
0.196611933241
0.104993585404
0.0451766597309
0.0176627062133
0.00664805667079

nonlin of deriv

0.00669285092428
0.0179862099621
0.0474258731776
0.119202922022
0.26894142137
0.5
0.73105857863
0.880797077978
0.952574126822
0.982013790038
0.993307149076
nonlin
